name: Full DevOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Install yamllint
       run: pip install yamllint
     - name: Run yamllint
       run: yamllint -- strict .
            # Optional: Add --strict to treat warnings as errors
            # run: yamllint --strict .
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_private_key: ${{ secrets.AWS_PRIVATE_KEY }}
        
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create Key File from Secret
      run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
  
    - name: Get EC2 IP
      id: get_ip
      run: echo "IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
      working-directory: terraform


    - name: Run Ansible
      run: |
         ansible-playbook ansible/playbooks/nginx_setup.yml \
         -i "$IP," \
         --private-key key.pem \
         -u ubuntu
      env:
        ANSIBLE_HOST_KEY_CHECKING: False

