---
name: Full DevOps CI/CD

"on":
  push:
    branches:
      - main
  pull_request:
    types: [opened]

jobs:
  yamllint:
    name: Run yamllint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint --strict .

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_private_key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Key File from Secret
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Get EC2 IP
        id: get_ip
        run: echo "IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Run Ansible
        run: |
          ansible-playbook ansible/playbooks/nginx_setup.yml \
            -i "$IP," \
            --private-key key.pem \
            -u ubuntu
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

  notify:
    name: Send PR Notification
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: sarikamarathe25@gmail.com
          password: Pujapatil@7177
          subject: 'New Pull Request Created'
          to: sarikamarathe25@gmail.com
          from: sarikamarathe25@gmail.com
          body: |
            A new pull request has been raised in the repo!
            📦 Repo: ${{ github.repository }}
            🔖 PR Title: ${{ github.event.pull_request.title }}
            👤 Author: ${{ github.event.pull_request.user.login }}
            🔗 PR URL: ${{ github.event.pull_request.html_url }}
          secure: true
