name: Full DevOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_private_key: ${{ secrets.AWS_PRIVATE_KEY }}
        
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create Key File from Secret
      run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
  
    - name: Get EC2 IP
      id: get_ip
      run: echo "IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

    - name: Run Ansible
      run: ansible-playbook -i "$IP," ansible/playbooks/nginx_setup.yml
    #- name: Run Ansible Playbook
    #  run: |
    #    ansible-playbook ansible/playbooks/nginx_setup.yml -i ansible/inventory.ini
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
